name: build

permissions:
  contents: read

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: build
        run: cargo build

  build-macos:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: build
        run: cargo build

  build-windows:
    runs-on: windows-latest
    steps:
      - name: install clang/llvm
        uses: KyleMayes/install-llvm-action@a7a1a882e2d06ebe05d5bb97c3e1f8c984ae96fc
        with:
          version: "20"
          directory: "${{ runner.temp }}/llvm-20"
      - name: configure clang/llvm environment
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: build
        run: cargo build
